language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y remove cmake
  - sudo apt-get -y install qt59base qt59multimedia qt59tools cmake libgles2-mesa-dev librtlsdr-dev libboost-all-dev libasound2-dev pulseaudio libopencv-dev libsqlite3-dev libxml2-dev bison flex libavcodec-dev libavformat-dev
  - source /opt/qt*/bin/qt*-env.sh

script:
  - mkdir build && cd build 
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install
  - mkdir -p appdir/usr/share/applications/ ; cp -r ../desktop/*.desktop appdir/usr/share/applications/ # FIXME; https://github.com/f4exb/sdrangel/issues/260
  - mkdir -p appdir/usr/share/icons/hicolor/scaleable/apps/ ; touch appdir/usr/share/icons/hicolor/scaleable/apps/sdrangel.svg # FIXME; https://github.com/f4exb/sdrangel/issues/259
  - sed -i -e 's|_icon.xpm||g' appdir/usr/share/applications/sdrangel.desktop # FIXME; https://github.com/f4exb/sdrangel/issues/259
  - find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file SDRangel*.AppImage https://transfer.sh/SDRangel-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh SDRangel*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
